---
title: "Conglomerados TIC"
author: "A. Paco M. Vino"
date: "August 3, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Importando librerias 
library(readxl)
library(readr)
library(ggplot2)
library(Amelia)
library(VIM)
library(mice)
library(grid)
library(gridExtra)
require(data.table)

```

# El contexto latinoamericano
# Separación lineal Vs. Clusters (Segmetanción de mercados)

# La encuesta

```{r cars echo= FALSE}
bd <- read_delim("bases de datos/base-5536-bdfinalcorregido.csv", 
     ";", escape_double = FALSE, trim_ws = TRUE)
```
```{r}

## definiendo algunas etiquetas comunes para los datos 
inter_no <- c("Internauta", "No Internauta")
si_no <- c("SI","NO") # 1 = Si , 2 = No





# Clasificando datos categóricos y datos numéricos
bd$Tipo <- as.factor(bd$Tipo)
levels(bd$Tipo) <- inter_no
bd$P2   <- as.factor(bd$P2) 
levels(bd$P2) <- si_no
bd$P4   <- as.factor(bd$P4)
levels(bd$P4)<- si_no
bd$P6   <- as.factor(bd$P6)
levels(bd$P6)<- si_no

bd$P10  <- as.factor(bd$P10)
bd$P12  <- as.factor(bd$P12)
bd$P15A <- as.factor(bd$P15A)
bd$P16  <- as.factor(bd$P16)
bd$P17  <- as.factor(bd$P17)
bd$P20  <- as.factor(bd$P20)
bd$P23  <- as.factor(bd$P23)
bd$P28  <- as.factor(bd$P28)
bd$P31A <- as.factor(bd$P31A) 
bd$P32  <- as.factor(bd$P32)
bd$P33  <- as.factor(bd$P33)
bd$P35  <- as.factor(bd$P35)

bd$P36A[bd$P36A==9] <- NA
bd$P36A  <- as.factor(bd$P36A)
bd$P129A[bd$P129A==9] <- NA
bd$P129A <- as.factor(bd$P129A)
bd$P130A[bd$P130A==9] <- NA
bd$P130A <- as.factor(bd$P130A)
bd$P131A[bd$P131A==9] <- NA
bd$P131A <- as.factor(bd$P131A)
bd$P132A[bd$P132A==9] <- NA
bd$P132A <- as.factor(bd$P132A)
bd$P133A[bd$P133A==9] <- NA
bd$P133A <- as.factor(bd$P133A)
bd$P134[bd$P134==9] <- NA
bd$P134  <- as.factor(bd$P134)
bd$P135[bd$P135==9] <- NA
bd$P135  <- as.factor(bd$P135)
bd$P136[bd$P136==9] <- NA
bd$P136  <- as.factor(bd$P136)
bd$P137[bd$P137==9] <- NA
bd$P137  <- as.factor(bd$P137)
bd$P138[bd$P138==9] <- NA
bd$P138  <- as.factor(bd$P138)
bd$P139[bd$P139==9] <- NA
bd$P139  <- as.factor(bd$P139)
bd$P140[bd$P140==9] <- NA
bd$P140  <- as.factor(bd$P140)

bd$P148  <- as.factor(bd$P148)
bd$P149  <- as.factor(bd$P149)
bd$P150  <- as.factor(bd$P150)
bd$P151  <- as.factor(bd$P151)
bd$P152  <- factor(bd$P152,labels = c("AS","CP","NP","PI","EM","ES","AC","RJ","SB","SN"))
bd$P153  <- as.factor(bd$P153)
bd$P154A <- as.factor(bd$P154A)
bd$P155  <- as.factor(bd$P155)
bd$P156A <- as.factor(bd$P156A)
bd$P156B <- as.factor(bd$P156B)
bd$P156C <- as.factor(bd$P156C)
bd$P156D <- as.factor(bd$P156D)
bd$P156E <- as.factor(bd$P156E)
bd$P156F <- as.factor(bd$P156F)
bd$P156G <- as.factor(bd$P156G)
bd$P156H <- as.factor(bd$P156H)
bd$P156I <- as.factor(bd$P156I)
bd$P156J <- as.factor(bd$P156J)
bd$P156K <- as.factor(bd$P156K)
bd$P157  <- as.factor(bd$P157)
bd$P158  <- as.factor(bd$P158)
bd$P159  <- as.factor(bd$P159)
bd$P160  <- as.factor(bd$P160) 
bd$CodP160 <- as.factor(bd$CodP160)
bd$Nse <- as.factor(bd$Nse)
bd$P14[bd$P14==9]  <- NA
bd$P30[bd$P30==99] <- NA
bd$P34[bd$P34==99] <- NA

```


```{r}
names(bd)
```


```{r}
# Ampliación de los factores de expansion

bd_dt <- as.data.table(bd)


expandido <- rep.row(bd_dt[1,], bd_dt$Ponderador5033)


```



```{r}
#Separando las bases de datos de internautas y NO internautas
NoInter <- bd[bd$Tipo == 2,]
Internautas <- bd[bd$Tipo == 1,]
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
